platform :ios, '7.0'
inhibit_all_warnings!

target "EditorDemo" do
  pod "WordPress-iOS-Editor", :path => "../"
  pod 'CocoaLumberjack', '~>1.8.1'
  pod 'UIAlertView+Blocks'
  pod 'WordPress-iOS-Shared', '~>0.0.5'
  pod 'WordPressCom-Analytics-iOS', :git => 'git://github.com/wordpress-mobile/WordPressCom-Analytics-iOS.git', :branch => 'feature/editor-updates'
end

target "EditorDemoTests" do
#   pod 'Expecta'
  pod 'CocoaLumberjack', '~>1.8.1'
end

