platform :ios, '7.0'
inhibit_all_warnings!

target "EditorDemo" do
  pod "WordPress-iOS-Editor", :path => "../"
  pod 'CocoaLumberjack', '~>1.8.1'
  pod 'WordPress-iOS-Shared', '0.0.1'
end

target "EditorDemoTests" do
#   pod 'Expecta'
end

